// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This callback file is created for your convenience. You may add application
// code to this file. If you regenerate this file over a previous version, the
// previous version will be overwritten and any code you have added will be
// lost.
#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include "rtos_bluetooth.h"
#include EMBER_AF_API_NVM3
#include "hal/hal.h"
#include "serial/serial.h"

/** @brief
 *
 * This function is called from the BLE stack to notify the application of a
 * stack event. After boot event it starts advertisement.
 */
void emberAfPluginBleEventCallback(struct gecko_cmd_packet* evt)
{
  static uint8_t boot_to_dfu = 0;

  // Handle stack events
  switch (BGLIB_MSG_ID(evt->header)) {
    // This boot event is generated when the system boots up after reset.
    // Do not call any stack commands before receiving the boot event.
    // Here the system is set to start advertising immediately after boot
    // procedure.
    case gecko_evt_system_boot_id:
      // Set advertising parameters. 100ms advertisement interval.
      // The first parameter is advertising set handle
      // The next two parameters are minimum and maximum advertising
      // interval, both in units of (milliseconds * 1.6).
      // The last two parameters are duration and maxevents left as default.
      gecko_cmd_le_gap_set_advertise_timing(0, 160, 160, 0, 0);
      // Start general advertising and enable connections.
      gecko_cmd_le_gap_start_advertising(0,
                                         le_gap_general_discoverable,
                                         le_gap_connectable_scannable);
      break;

    case gecko_evt_le_connection_closed_id:
      // Check if need to boot to dfu mode.
      if (boot_to_dfu) {
        // Enter to DFU OTA mode.
        gecko_cmd_system_reset(2);
      } else {
        // Restart advertising after client has disconnected.
        gecko_cmd_le_gap_start_advertising(0,
                                           le_gap_general_discoverable,
                                           le_gap_connectable_scannable);
      }
      break;
  }
}
