#define CREATOR_CONNECT_DEVICE_NODE_ID  0x000A
// This key is used for an indexed token
#define NVM3KEY_CONNECT_DEVICE_NODE_ID (NVM3KEY_DOMAIN_USER | 0x000A)

#ifdef DEFINETOKENS
#define CONNECT_DEVICE_NODE_ID_SIZE uint16_t

DEFINE_BASIC_TOKEN(CONNECT_DEVICE_NODE_ID,
                   CONNECT_DEVICE_NODE_ID_SIZE,
                   0x0000)
#endif //DEFINETOKENS
